 - hosts: all
   tasks:
      - name: Copy a file to managed hosts
        ansible.builtin.copy:
           src: "/var/lib/awx/projects/abhi_ansible/f.tar"
           dest: "/tmp"
      - name: Install the latest fireeye
        ansible.builtin.shell:
           cmd: "tar -xvf  /tmp/f.tar"
